import Foundation
import ReplayCore

// Checks this port against the Glaze app, not against itself.
//
// `spec/` holds the schema, the behavioural constants, and — most importantly —
// session derivation run against real inputs with the output the Glaze
// implementation actually produced. All of it generated by tools/sync-spec.mjs.
//
//     swift run replay-parity
//
// A failure here after regenerating the spec means the reference behaviour moved and
// this port has not caught up. That is the whole point: it turns "did I port that
// change correctly?" into a question with a yes-or-no answer.

// ── the generated contract ────────────────────────────────────────────────────

struct Fixture: Decodable {
    struct Event: Decodable {
        let id: Int64
        let type: String
        let applicationName: String
        let bundleIdentifier: String?
        let appPath: String?
        let startedAt: Int64
        let endedAt: Int64?
        let duration: Int
    }
    struct App: Decodable {
        let applicationName: String
        let bundleIdentifier: String?
        let seconds: Int
        let switches: Int
        let share: Double
    }
    struct Item: Decodable {
        let kind: String
        let title: String?
        let category: String?
        let spanSeconds: Int?
        let activeSeconds: Int?
        let switches: Int?
        let eventIds: [Int64]?
        let apps: [App]?
        let reason: String?
        let applicationName: String?
        let startedAt: Int64
        let endedAt: Int64
        let seconds: Int?
    }
    let name: String
    let description: String
    let now: Int64
    let events: [Event]
    let expected: [Item]
}

struct Constants: Decodable {
    struct Tracker: Decodable {
        let awayAfterSeconds: Int
        let idlePollMs: Int
        let pointEventDedupeMs: Int
        let ignoredBundleIds: [String]
    }
    struct Store: Decodable {
        let idleStretchSeconds: Int
        let compactMinFreeRatio: Double
        let compactMinFreePages: Int
        let deleteChunk: Int
    }
    struct CategoryPattern: Decodable {
        let category: String
        let pattern: String
    }
    struct Derivation: Decodable {
        let idleBreakSeconds: Int
        let recordingGapSeconds: Int
        let minSessionSeconds: Int
        let categoryPatterns: [CategoryPattern]
    }
    let glazeVersion: String
    let glazeCommit: String
    let tracker: Tracker
    let store: Store
    let derivation: Derivation
}

// ── reporting ─────────────────────────────────────────────────────────────────

// Top-level code in an executable runs on the main actor, so the counters and the
// helpers that touch them are main-actor-isolated too.
var failures: [String] = []
var checks = 0

@MainActor func expect(_ condition: Bool, _ what: String) {
    checks += 1
    if !condition { failures.append(what) }
}

@MainActor func expectEqual<T: Equatable>(_ actual: T, _ expected: T, _ what: String) {
    checks += 1
    if actual != expected { failures.append("\(what)\n      got \(actual)\n      want \(expected)") }
}

func section(_ title: String) { print("── \(title)") }

// ── locating spec/ ────────────────────────────────────────────────────────────

/// `spec/` lives beside the package, not inside the build products, so it is found
/// relative to this source file — or from an explicit path, for CI.
let specRoot: URL = {
    if let argument = CommandLine.arguments.dropFirst().first {
        return URL(fileURLWithPath: argument)
    }
    var root = URL(fileURLWithPath: #filePath)
    for _ in 0..<3 { root.deleteLastPathComponent() }   // Sources/ReplayParity/main.swift
    return root.appendingPathComponent("spec")
}()

func load<T: Decodable>(_ type: T.Type, _ relative: String) throws -> T {
    let url = specRoot.appendingPathComponent(relative)
    return try JSONDecoder().decode(type, from: Data(contentsOf: url))
}

func event(_ raw: Fixture.Event) -> ActivityEvent {
    ActivityEvent(
        id: raw.id,
        type: EventType(rawValue: raw.type) ?? .activated,
        applicationName: raw.applicationName,
        bundleIdentifier: raw.bundleIdentifier,
        appPath: raw.appPath,
        startedAt: raw.startedAt,
        endedAt: raw.endedAt,
        duration: raw.duration
    )
}

// ── run ───────────────────────────────────────────────────────────────────────

do {
    let constants = try load(Constants.self, "constants.json")
    print("Checking this port against Glaze \(constants.glazeVersion) (\(constants.glazeCommit))")
    print("spec: \(specRoot.path)\n")

    section("constants")
    expectEqual(Rules.awayAfterSeconds, constants.tracker.awayAfterSeconds, "awayAfterSeconds")
    expectEqual(Int(Rules.idlePollSeconds * 1000), constants.tracker.idlePollMs, "idlePollMs")
    expectEqual(
        Int(Rules.pointEventDedupeSeconds * 1000),
        constants.tracker.pointEventDedupeMs,
        "pointEventDedupeMs"
    )
    expectEqual(
        Rules.ignoredBundleIDs.sorted(),
        constants.tracker.ignoredBundleIds.sorted(),
        "ignoredBundleIDs"
    )
    expectEqual(Rules.idleStretchSeconds, constants.store.idleStretchSeconds, "idleStretchSeconds")
    expectEqual(Rules.compactMinFreeRatio, constants.store.compactMinFreeRatio, "compactMinFreeRatio")
    expectEqual(Rules.compactMinFreePages, constants.store.compactMinFreePages, "compactMinFreePages")
    expectEqual(Rules.deleteChunk, constants.store.deleteChunk, "deleteChunk")
    expectEqual(Rules.idleBreakSeconds, constants.derivation.idleBreakSeconds, "idleBreakSeconds")
    expectEqual(
        Rules.recordingGapSeconds,
        constants.derivation.recordingGapSeconds,
        "recordingGapSeconds"
    )
    expectEqual(Rules.minSessionSeconds, constants.derivation.minSessionSeconds, "minSessionSeconds")

    section("category table (order matters — first match wins, and it names the session)")
    for entry in constants.derivation.categoryPatterns {
        // Probe with the pattern's first alternative, minus its anchors.
        let probe = entry.pattern
            .split(separator: "|").first
            .map {
                String($0)
                    .replacingOccurrences(of: "^", with: "")
                    .replacingOccurrences(of: "$", with: "")
            } ?? ""
        guard !probe.isEmpty else { continue }
        expectEqual(categorizeApp(probe).rawValue, entry.category, "categorizeApp(\"\(probe)\")")
    }

    section("schema")
    let generatedSchema = try String(
        contentsOf: specRoot.appendingPathComponent("schema.sql"),
        encoding: .utf8
    )
    func normalise(_ sql: String) -> String {
        sql.split(separator: "\n")
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty && !$0.hasPrefix("--") }
            .joined(separator: " ")
    }
    expectEqual(
        normalise(ActivityStore.schemaForParityCheck),
        normalise(generatedSchema),
        "ActivityStore.schema matches spec/schema.sql"
    )

    section("session derivation")
    struct Index: Decodable { let fixtures: [String] }
    let index = try load(Index.self, "fixtures/index.json")
    for name in index.fixtures {
        let fixture = try load(Fixture.self, "fixtures/\(name).json")
        let produced = buildTimeline(fixture.events.map(event), now: fixture.now)

        expectEqual(produced.count, fixture.expected.count, "\(name): number of items")
        guard produced.count == fixture.expected.count else {
            print("   ✗ \(name) — \(fixture.description)")
            continue
        }

        let before = failures.count
        for (offset, expected) in fixture.expected.enumerated() {
            switch produced[offset] {
            case .session(let session):
                expectEqual("session", expected.kind, "\(name)[\(offset)]: kind")
                expectEqual(session.title, expected.title ?? "", "\(name)[\(offset)]: title")
                expectEqual(
                    session.category.rawValue,
                    expected.category ?? "",
                    "\(name)[\(offset)]: category"
                )
                expectEqual(session.startedAt, expected.startedAt, "\(name)[\(offset)]: startedAt")
                expectEqual(session.endedAt, expected.endedAt, "\(name)[\(offset)]: endedAt")
                expectEqual(
                    session.spanSeconds,
                    expected.spanSeconds ?? -1,
                    "\(name)[\(offset)]: spanSeconds"
                )
                expectEqual(
                    session.activeSeconds,
                    expected.activeSeconds ?? -1,
                    "\(name)[\(offset)]: activeSeconds"
                )
                expectEqual(session.switches, expected.switches ?? -1, "\(name)[\(offset)]: switches")
                expectEqual(
                    session.events.map(\.id),
                    expected.eventIds ?? [],
                    "\(name)[\(offset)]: rows the session is made of"
                )
                expectEqual(
                    session.apps.map(\.applicationName),
                    (expected.apps ?? []).map(\.applicationName),
                    "\(name)[\(offset)]: app order"
                )
                for (app, expectedApp) in zip(session.apps, expected.apps ?? []) {
                    expectEqual(app.seconds, expectedApp.seconds, "\(name): \(app.applicationName) seconds")
                    expectEqual(app.switches, expectedApp.switches, "\(name): \(app.applicationName) switches")
                    expect(
                        abs(app.share - expectedApp.share) < 0.000_01,
                        "\(name): \(app.applicationName) share — got \(app.share), want \(expectedApp.share)"
                    )
                }

            case .breakItem(let gap):
                expectEqual("break", expected.kind, "\(name)[\(offset)]: kind")
                expectEqual(gap.reason.rawValue, expected.reason ?? "", "\(name)[\(offset)]: reason")
                expectEqual(gap.startedAt, expected.startedAt, "\(name)[\(offset)]: startedAt")
                expectEqual(gap.endedAt, expected.endedAt, "\(name)[\(offset)]: endedAt")
                expectEqual(gap.seconds, expected.seconds ?? -1, "\(name)[\(offset)]: seconds")
                expectEqual(
                    gap.applicationName,
                    expected.applicationName,
                    "\(name)[\(offset)]: applicationName"
                )
            }
        }
        print("   \(failures.count == before ? "✓" : "✗") \(name) — \(fixture.description)")
    }

    section("store round-trip")
    let tmp = URL(fileURLWithPath: NSTemporaryDirectory())
        .appendingPathComponent("replay-parity-\(UUID().uuidString).db")
    let store = ActivityStore(path: tmp.path)
    try store.open()
    let t0 = Int64(1_770_000_000_000)
    let id = try store.openSession(name: "Code", bundleID: "com.microsoft.VSCode", appPath: nil, startedAt: t0)
    try store.closeSession(id: id, endedAt: t0 + 600_000)
    try store.recordAway(startedAt: t0 + 600_000, endedAt: t0 + 1_200_000)
    expectEqual(try store.countRows(), 2, "two rows written")
    let read = try store.sessions(from: startOfLocalDay(t0), to: startOfLocalDay(t0) + dayMillis)
    expectEqual(read.count, 2, "both rows read back")
    expectEqual(read.first?.duration, 600, "duration computed by SQL, in seconds")
    expectEqual(try store.reclaimableBytes(), 0, "a fresh database has nothing to reclaim")
    expect(store.integrityCheck().ok, "integrity check passes")
    let deleted = try store.deleteEvents(ids: [id])
    expectEqual(deleted.removed, 1, "delete by id removes one row")
    expectEqual(deleted.dayStarts, [startOfLocalDay(t0)], "and reports the day it fell on")
    store.close()
    try? FileManager.default.removeItem(at: tmp)

    print("")
    if failures.isEmpty {
        print("PARITY OK — \(checks) checks against Glaze \(constants.glazeVersion)")
        exit(0)
    }
    print("PARITY FAILED — \(failures.count) of \(checks) checks")
    for failure in failures { print("  · \(failure)") }
    print("""

        Either this port needs updating to match the Glaze app, or spec/ is stale.
        Regenerate with: node tools/sync-spec.mjs
        """)
    exit(1)
} catch {
    print("could not run the parity check: \(error)")
    print("is spec/ generated? run: node tools/sync-spec.mjs")
    exit(2)
}
