-- Generated by tools/sync-spec.mjs — do not edit by hand.
-- Glaze app version 2.3.1, commit 9dcd1bb.
--
-- The one file both implementations must agree on byte for byte: a database
-- written by one has to be readable by the other.

CREATE TABLE IF NOT EXISTS events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  type TEXT NOT NULL,
  application_name TEXT NOT NULL,
  bundle_identifier TEXT,
  started_at INTEGER NOT NULL,
  ended_at INTEGER,
  duration INTEGER NOT NULL DEFAULT 0,
  metadata TEXT
);
CREATE INDEX IF NOT EXISTS idx_events_started ON events(started_at);
CREATE INDEX IF NOT EXISTS idx_events_type ON events(type);

CREATE TABLE IF NOT EXISTS daily_summaries (
  day_start INTEGER PRIMARY KEY,
  active_seconds INTEGER NOT NULL,
  top_bundle_id TEXT,
  top_app_name TEXT,
  top_seconds INTEGER NOT NULL DEFAULT 0,
  updated_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS reflections (
  day_start INTEGER PRIMARY KEY,
  text TEXT NOT NULL,
  updated_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS annotations (
  session_start INTEGER PRIMARY KEY,
  note TEXT,
  bookmarked INTEGER NOT NULL DEFAULT 0,
  tags TEXT,
  updated_at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_annotations_bookmarked ON annotations(bookmarked);
