import Foundation
import ParityKit
import Testing

@testable import ReplayCore

/// Checks this port against the Glaze app, not against itself.
///
/// `spec/` is generated by `tools/sync-spec.mjs` from the Glaze sources, and
/// `spec/fixtures/` holds the output its session derivation *actually produced* for a set
/// of inputs. So a failure here after regenerating the spec means the reference
/// behaviour moved and this port has not caught up — which is the entire point.
///
/// The same suite runs as `swift run replay-parity` for environments without Xcode; both
/// call `ParityKit.runAllChecks`, so there is nothing to keep in step.
@Suite("Parity with the Glaze reference implementation")
struct ParityTests {

    static let report: ParityKit.Report = {
        do { return try ParityKit.runAllChecks() } catch {
            fatalError("could not load spec/ — run `node tools/sync-spec.mjs`: \(error)")
        }
    }()

    @Test("spec/ names the Glaze version it was generated from")
    func specProvenance() {
        #expect(!Self.report.glazeVersion.isEmpty)
        #expect(!Self.report.glazeCommit.isEmpty)
        #expect(!Self.report.checks.isEmpty)
    }

    @Test("Rules match the generated constants")
    func constants() {
        for check in Self.report.checks where check.group == "constants" {
            #expect(check.passed, "\(check.what): \(check.detail ?? "")")
        }
    }

    /// Order matters: the first matching pattern wins, and it decides the session's name.
    @Test("The category table matches, in order")
    func categoryTable() {
        for check in Self.report.checks where check.group == "category table" {
            #expect(check.passed, "\(check.what): \(check.detail ?? "")")
        }
    }

    /// A database written by either implementation has to be readable by the other.
    @Test("The store's schema matches spec/schema.sql")
    func schema() {
        for check in Self.report.checks where check.group == "schema" {
            #expect(check.passed, "\(check.what): \(check.detail ?? "")")
        }
    }

    @Test(
        "Session derivation reproduces the Glaze output",
        arguments: ParityTests.report.fixtureResults.map(\.name)
    )
    func derivation(fixture: String) {
        let group = "derivation/\(fixture)"
        let checks = Self.report.checks.filter { $0.group == group }
        #expect(!checks.isEmpty, "no checks ran for \(fixture)")
        for check in checks {
            #expect(check.passed, "\(check.what): \(check.detail ?? "")")
        }
    }

    @Test("The store round-trips against a real SQLite file")
    func storeRoundTrip() {
        for check in Self.report.checks where check.group == "store round-trip" {
            #expect(check.passed, "\(check.what): \(check.detail ?? "")")
        }
    }

    @Test("Every check passed")
    func everythingPassed() {
        let summary = Self.report.failures
            .map { "[\($0.group)] \($0.what) — \($0.detail ?? "")" }
            .joined(separator: "\n")
        #expect(Self.report.passed, "\(Self.report.failures.count) failed:\n\(summary)")
    }
}
